# cluster_config.yml - cluster configuration
__default__:
    account: sejoslin
    partition: bigmemh
    time: 32:16:32
    nodes: 1
    ntasks: 32
    memory: 480Gb
    chdir: /home/sejoslin/git_repos/genome_assembly
    jobname: "{rule}"
    output: "jobs/slurm/snakemake.j%j.{rule}.out"
    error: "jobs/slurm/snakemake.j%j.{rule}.err"

big_mem:
    partition: bigmemh
    time: 02-04:08:16
    nodes: 1
    ntasks: 12
    memory: MaxMemPerNode
